cors:
  originPatterns: http://localhost:3000,http://localhost:8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_cleanarch_ddd?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
springdoc:
  pathsToMatch: /api/v1/**
  swagger-ui:
    use-root-path: true